[package]
name = "chat"
version = "0.1.1"
authors = ["Kenta Iwasaki <kenta@perlin.net>"]
edition = "2018"

[profile.release]
lto = true

[lib]
crate-type = ["cdylib"]

[dependencies]
smart-contract = "0.2.0"
smart-contract-macros = "0.2.0"